<a href="https://colab.research.google.com/github/Mat9408/Ciencia_de_Dados_Praticas/blob/main/Ci%C3%AAncia_de_Dados_Dataset_Clima.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Atividade de Ciência de Dados
Matheus da Cunha Alves - 2022101251

In [ ]:
#Importando o Pandas
import pandas as pd

In [ ]:
#Importando a base de dados em csv
df = pd.read_csv('clima.csv', sep=';')

In [ ]:
#Visualizando as 5 primeiras linhas do DataFrame
df.head()

    Aparência  Temperatura  Umidade  Vento Jogar
0  Ensolarado           85       85  Fraco   Não
1  Ensolarado           80       90  Forte   Não
2     Nublado           83       86  Fraco   Sim
3     Chuvoso           70       96  Fraco   Sim
4     Chuvoso           68       80  Fraco   Sim

In [ ]:
#Visualizando as 5 últimas linhas do DataFrame
df.tail()

     Aparência  Temperatura  Umidade  Vento Jogar
9      Chuvoso           75       80  Fraco   Sim
10  Ensolarado           75       70  Forte   Sim
11     Nublado           72       90  Forte   Sim
12     Nublado           81       75  Fraco   Sim
13     Chuvoso           71       91  Forte   Não

In [ ]:
#Verificando o tamanho do DataFrame
df.shape

(14, 5)

In [ ]:
#visualizando as primeiras e últimas linhas e tamanho do DataFrame
display(df)

     Aparência  Temperatura  Umidade  Vento Jogar
0   Ensolarado           85       85  Fraco   Não
1   Ensolarado           80       90  Forte   Não
2      Nublado           83       86  Fraco   Sim
3      Chuvoso           70       96  Fraco   Sim
4      Chuvoso           68       80  Fraco   Sim
5      Chuvoso           65       70  Forte   Não
6      Nublado           64       65  Forte   Sim
7   Ensolarado           72       95  Fraco   Não
8   Ensolarado           69       70  Fraco   Sim
9      Chuvoso           75       80  Fraco   Sim
10  Ensolarado           75       70  Forte   Sim
11     Nublado           72       90  Forte   Sim
12     Nublado           81       75  Fraco   Sim
13     Chuvoso           71       91  Forte   Não

In [ ]:
#Mostrando somente os tipos dos dados
df.dtypes

Aparência      object
Temperatura     int64
Umidade         int64
Vento          object
Jogar          object
dtype: object

In [ ]:
#Mostrando o tipo de dados e os valores vazios
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Aparência    14 non-null     object
 1   Temperatura  14 non-null     int64
 2   Umidade      14 non-null     int64
 3   Vento        14 non-null     object
 4   Jogar        14 non-null     object
dtypes: int64(2), object(3)
memory usage: 692.0+ bytes

In [ ]:
#Contando os valores vazios por coluna
df.isnull().sum()

Aparência      0
Temperatura    0
Umidade        0
Vento          0
Jogar          0
dtype: int64

Principais conceitos estatísticos

In [ ]:
dados = {
    'X': [1,2,3,4,5,6,7,8,9,10,11]
}

dados= pd.DataFrame(dados)

In [ ]:
#Mostrando a média
dados.mean()

X    6.0
dtype: float64

In [ ]:
#Mostrando a contagem de registros
dados.count()

X    11
dtype: int64

In [ ]:
#Calculando a mediana
dados.median()

X    6.0
dtype: float64

In [ ]:
#Desvio Padrão
dados.std()

X    3.316625
dtype: float64

In [ ]:
#Trazendo o resumo estatístico utilizando o describe
dados.describe()

               X
count  11.000000
mean    6.000000
std     3.316625
min     1.000000
25%     3.500000
50%     6.000000
75%     8.500000
max    11.000000

Voltando para a base do nosso problema

In [ ]:
#Trazendo o resumo estatístico para a nossa base
df.describe()

       Temperatura    Umidade
count    14.000000  14.000000
mean     73.571429  81.642857
std       6.571667  10.285218
min      64.000000  65.000000
25%      69.250000  71.250000
50%      72.000000  82.500000
75%      78.750000  90.000000
max      85.000000  96.000000

Escolhendo colunas da base

In [ ]:
#Buscando por uma coluna.
#Podemos usar o nome da coluna entre aspas

df['Temperatura']

0     85
1     80
2     83
3     70
4     68
5     65
6     64
7     72
8     69
9     75
10    75
11    72
12    81
13    71
Name: Temperatura, dtype: int64

In [ ]:
#Ou usar o ponto
df.Temperatura

0     85
1     80
2     83
3     70
4     68
5     65
6     64
7     72
8     69
9     75
10    75
11    72
12    81
13    71
Name: Temperatura, dtype: int64

In [ ]:
#Usando uma coluna, podemos contar a quantidade de vezes em que cada valor aparece
df.Temperatura.value_counts()

Temperatura
75    2
72    2
85    1
80    1
70    1
83    1
65    1
68    1
64    1
69    1
81    1
71    1
Name: count, dtype: int64

In [ ]:
#Selecionando um conjunto de colunas
df[['Temperatura','Umidade','Vento']]

    Temperatura  Umidade  Vento
0            85       85  Fraco
1            80       90  Forte
2            83       86  Fraco
3            70       96  Fraco
4            68       80  Fraco
5            65       70  Forte
6            64       65  Forte
7            72       95  Fraco
8            69       70  Fraco
9            75       80  Fraco
10           75       70  Forte
11           72       90  Forte
12           81       75  Fraco
13           71       91  Forte

Também conseguimos fazer filtros na base

In [ ]:
#Visualizando novamente o DataFrame
df.head()

    Aparência  Temperatura  Umidade  Vento Jogar
0  Ensolarado           85       85  Fraco   Não
1  Ensolarado           80       90  Forte   Não
2     Nublado           83       86  Fraco   Sim
3     Chuvoso           70       96  Fraco   Sim
4     Chuvoso           68       80  Fraco   Sim

In [ ]:
#Verificando temperaturas maiores que 80
df[df.Temperatura > 80]

     Aparência  Temperatura  Umidade  Vento Jogar
0   Ensolarado           85       85  Fraco   Não
2      Nublado           83       86  Fraco   Sim
12     Nublado           81       75  Fraco   Sim

In [ ]:
#Verificando temperaturas menores que 70
df[df.Temperatura <70]

    Aparência  Temperatura  Umidade  Vento Jogar
4     Chuvoso           68       80  Fraco   Sim
5     Chuvoso           65       70  Forte   Não
6     Nublado           64       65  Forte   Sim
8  Ensolarado           69       70  Fraco   Sim

Usando filtros de E e OU

In [ ]:
#Verificando se há temperatura E umidade maiores que 80
df[(df.Temperatura > 80) & (df.Umidade > 80)].head()

    Aparência  Temperatura  Umidade  Vento Jogar
0  Ensolarado           85       85  Fraco   Não
2     Nublado           83       86  Fraco   Sim

Uma forma muito útil de fazer seleção de dados é usando o .loc() ou o .iloc()

In [ ]:
#O .loc() permite fazer a busca da mesma forma acima
df.loc[(df.Temperatura > 1) & (df.Umidade > 1)].head()

    Aparência  Temperatura  Umidade  Vento Jogar
0  Ensolarado           85       85  Fraco   Não
1  Ensolarado           80       90  Forte   Não
2     Nublado           83       86  Fraco   Sim
3     Chuvoso           70       96  Fraco   Sim
4     Chuvoso           68       80  Fraco   Sim

In [ ]:
#Ele também permite usar argumento lógicos
df.loc[(df.Temperatura > 1) | (df.Umidade > 1)].head()

    Aparência  Temperatura  Umidade  Vento Jogar
0  Ensolarado           85       85  Fraco   Não
1  Ensolarado           80       90  Forte   Não
2     Nublado           83       86  Fraco   Sim
3     Chuvoso           70       96  Fraco   Sim
4     Chuvoso           68       80  Fraco   Sim

In [ ]:
#Ele permite filtrar colunas de forma muito prática
df.loc[(df.Temperatura > 1) | (df.Umidade > 1), ['Aparência','Jogar']].head()

    Aparência Jogar
0  Ensolarado   Não
1  Ensolarado   Não
2     Nublado   Sim
3     Chuvoso   Sim
4     Chuvoso   Sim

Já o .iloc() vai usar o índice para filtrar

In [ ]:
#Buscando as linhas de 3(inclusive) a 4(exclusive)
df.iloc[3:4]

  Aparência  Temperatura  Umidade  Vento Jogar
3   Chuvoso           70       96  Fraco   Sim

In [ ]:
#Também posso usar para buscar apenas colunas específicas
df.iloc[3:7, 1:3]

   Temperatura  Umidade
3           70       96
4           68       80
5           65       70
6           64       65