<a href="https://colab.research.google.com/github/Mat9408/Ciencia_de_Dados_Praticas/blob/main/Ci%C3%AAncia_de_Dados_Aula_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_left = pd.DataFrame({
'Student_ID': ['001', '002', '003', '004', '005'],
'Gender': ['F', 'M', 'F', 'F', 'M'],
'race_ethnicity': ['Group A', 'Group B', 'Group D', 'Group E','Group E']
})
df_right = pd.DataFrame({
'Student_ID': ['002', '003', '005', '006', '007'],
'Math': [77, 46, 83, 53, 65],
'Reading': [91, 62, 88, 56, 72],
'Writing': [49, 90, 67, 66, 59]
})

In [ ]:
df_left.merge(df_right, on='Student_ID', how='left')

  Student_ID Gender race_ethnicity  Math  Reading  Writing
0        001      F        Group A   NaN      NaN      NaN
1        002      M        Group B  77.0     91.0     49.0
2        003      F        Group D  46.0     62.0     90.0
3        004      F        Group E   NaN      NaN      NaN
4        005      M        Group E  83.0     88.0     67.0

In [ ]:
df_left.merge(df_right, on='Student_ID', how='right')

  Student_ID Gender race_ethnicity  Math  Reading  Writing
0        002      M        Group B    77       91       49
1        003      F        Group D    46       62       90
2        005      M        Group E    83       88       67
3        006    NaN            NaN    53       56       66
4        007    NaN            NaN    65       72       59

In [ ]:
df_left.merge(df_right, on='Student_ID', how='inner')

  Student_ID Gender race_ethnicity  Math  Reading  Writing
0        002      M        Group B    77       91       49
1        003      F        Group D    46       62       90
2        005      M        Group E    83       88       67

In [ ]:
df_left.merge(df_right, on='Student_ID', how='outer')

  Student_ID Gender race_ethnicity  Math  Reading  Writing
0        001      F        Group A   NaN      NaN      NaN
1        002      M        Group B  77.0     91.0     49.0
2        003      F        Group D  46.0     62.0     90.0
3        004      F        Group E   NaN      NaN      NaN
4        005      M        Group E  83.0     88.0     67.0
5        006    NaN            NaN  53.0     56.0     66.0
6        007    NaN            NaN  65.0     72.0     59.0

In [ ]:
df_left.merge(df_right[['Student_ID','Reading']],on='Student_ID', how='left')

  Student_ID Gender race_ethnicity  Reading
0        001      F        Group A      NaN
1        002      M        Group B     91.0
2        003      F        Group D     62.0
3        004      F        Group E      NaN
4        005      M        Group E     88.0